# Generated by Django 5.2.5 on 2025-09-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.TextField(max_length=128, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
