# Generated by Django 5.2.5 on 2025-09-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_country_deleted_at_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.city'),
        ),
    ]
