# Generated by Django 5.2.5 on 2025-09-10 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_address_user_created_at_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='user',
            name='city_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='authentication.city'),
            preserve_default=False,
        ),
    ]
